version: "3.8"

services:
  postgres-booking:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_BOOKING_NAME}
      POSTGRES_USER: ${DB_BOOKING_USER}
      POSTGRES_PASSWORD: ${DB_BOOKING_PASSWORD}
    ports:
      - "${DB_BOOKING_PORT}:5431"

  postgres-hotel:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_HOTEL_NAME}
      POSTGRES_USER: ${DB_HOTEL_USER}
      POSTGRES_PASSWORD: ${DB_HOTEL_PASSWORD}
    ports:
      - "${DB_HOTEL_PORT}:5432"

  booking-svc:
    build:
      context: .
      dockerfile: cmd/booking-svc/Dockerfile
    ports:
      - "${BOOKING_PORT}:50051"
      - "${BOOKING_CONN_PORT}:8080"
    environment:
      - DATABASE_URL=${BOOKING_DB_URL}

  hotel-svc:
    build:
      context: .
      dockerfile: cmd/hotel-svc/Dockerfile
    ports:
      - "${HOTEL_PORT}:50052"
    environment:
      - DATABASE_URL=${HOTEL_DB_URL}

  notification-svc:
    build:
      context: .
      dockerfile: cmd/notification-svc/Dockerfile
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "${PROM_PORT}:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: unless-stopped
    depends_on:
      - prometheus 
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER} 
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    depends_on:
      - zookeeper
    container_name: kafka
    restart: always
    image: wurstmeister/kafka:latest
    ports:
      - "${KAFKA_PORT}:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    
volumes:
  prom_data:
